In [1]:
#%% NumPy  - Python scientific library
import numpy as np

In [2]:
# arange() works similar to range()
np.arange(1, 9, 2)

array([1, 3, 5, 7])

In [3]:
# reshape defines the array dimensions
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
# creates an array from a list
np.array([[1,-2],[5,3]])

array([[ 1, -2],
       [ 5,  3]])

In [5]:
# creates an array with zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# creates an array of type int with ones 
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [7]:
# creates an array from a csv file
np.genfromtxt('data.csv', delimiter=";")

OSError: data.csv not found.

In [8]:
# Product of two arrays in Python
a = [1,2,3]
b = [6,5,4]
c = list()
for i in range(len(a)):
    c.append(a[i] * b[i])
print(c)

[6, 10, 12]


In [9]:
# Product of two arrays unsing NumPy 
# arrays must be declared
a = np.array([1,2,3])
b = np.array([6,5,4])
c = a * b
c

array([ 6, 10, 12])

**Basic operations**

In [10]:
a - b

array([-5, -3, -1])

In [11]:
b**2

array([36, 25, 16], dtype=int32)

In [12]:
5 * np.sqrt(a)

array([5.        , 7.07106781, 8.66025404])

In [13]:
a > 2

array([False, False,  True])

In [14]:
# Inner product
c = np.dot(a,b)
c = np.inner(a,b)
c

28

**Matrix/vector operations**

In [15]:
ma = np.array([[1,-2],[5,3]])
ma

array([[ 1, -2],
       [ 5,  3]])

In [16]:
mb = np.array([[-1,2],[4,1]])
mb

array([[-1,  2],
       [ 4,  1]])

In [20]:
# Matrix product
ma @ mb
np.dot(ma,mb)

array([[-9,  0],
       [ 7, 13]])

In [21]:
# Matrix transpose
np.transpose(ma)

array([[ 1,  5],
       [-2,  3]])

In [22]:
# Matrix determinant
np.linalg.det(ma)

13.0

In [23]:
# Matrix inverse
np.linalg.inv(ma)

array([[ 0.23076923,  0.15384615],
       [-0.38461538,  0.07692308]])

In [24]:
# Matrix flatten
ma.flatten()

array([ 1, -2,  5,  3])

In [25]:
#%% Python and numpy time comparison
import numpy as np
import time
a = range(1, 10000001)
b = range(1,10000001)
c = list()
t1 = time.perf_counter()
for i in range(len(a)):
    c.append(a[i] / b[i])
t2 = time.perf_counter()
print(f'Python time: {t2 - t1:0.4}')

Python time: 3.212


In [26]:
a = np.arange(1,1000001)
b = np.arange(1,1000001)
t1 = time.perf_counter()
c = a / b
t2 = time.perf_counter()
print(f'NumPy time: {t2 - t1:0.4}')

NumPy time: 0.4096
